// Data for Nexara — Journal of Computational Cognition
// All names, titles, DOIs, metrics are fictional.

const JOURNAL = {
  name: "Journal of Computational Cognition",
  short: "J. Comput. Cognition",
  founded: 2008,
  issn_online: "2845-1739",
  issn_print: "2845-1720",
  doiPrefix: "10.31472/jcc",
  frequency: "Quarterly · 4 issues / year",
  impact: "6.42",
  acceptance: "18%",
  citeScore: "9.1",
  timeToFirstDecision: "31 days",
  tagline: "A peer-reviewed, fully open-access venue for theoretical, computational, and empirical work at the intersection of cognition, learning systems, and neural computation.",
  currentVolume: 18,
  currentIssue: 2,
  currentDate: "May 2026",
  editorChief: { name: "Helena Vásquez", aff: "MIT, Cambridge", init: "HV" },
  editors: [
    { name: "Marek Tóth", role: "Deputy Editor", aff: "ETH Zürich", init: "MT" },
    { name: "Ayanna Okafor", role: "Methods Editor", aff: "UCL", init: "AO" },
    { name: "Rohan Iyer", role: "Statistics Editor", aff: "Stanford University", init: "RI" },
    { name: "Sofía Castellanos", role: "Reviews Editor", aff: "Max Planck Inst.", init: "SC" },
  ],
};

const SUBJECTS = [
  "Reinforcement Learning",
  "Neural Computation",
  "Memory & Recall",
  "Decision Making",
  "Bayesian Cognition",
  "Language & Symbols",
  "Computational Psychiatry",
  "Reviews & Tutorials",
];

const ARTICLES = [
  {
    id: "a1",
    type: "Research Article",
    oa: true,
    subject: "Reinforcement Learning",
    title: "Successor representations emerge from sparse predictive coding in recurrent networks",
    authors: [
      { name: "L. Marchetti", corresp: true, aff: 1 },
      { name: "P. Adebayo", aff: 1 },
      { name: "K. Schäfer", aff: 2 },
      { name: "H. Vásquez", aff: 3 },
    ],
    affiliations: [
      "Department of Computational Neuroscience, ETH Zürich",
      "Bernstein Center, Humboldt-Universität zu Berlin",
      "MIT Department of Brain & Cognitive Sciences",
    ],
    abstract: "We show that sparse predictive coding objectives, when paired with mild structural constraints on recurrent connectivity, give rise to representations functionally equivalent to the successor representation. Networks trained on naturalistic trajectories develop place-cell-like and grid-cell-like populations without explicit reward signals, suggesting a unifying account of spatial and reward-prediction coding.",
    doi: "10.31472/jcc.2026.0418",
    pages: "104–138",
    volume: 18,
    issue: 2,
    year: 2026,
    publishedOn: "May 14, 2026",
    receivedOn: "Nov 9, 2025",
    citations: 12,
    downloads: "3,184",
    altmetric: 142,
    altmetricBreakdown: { news: 4, twitter: 38, blogs: 6, policy: 1 },
    keywords: ["successor representation", "predictive coding", "hippocampus", "RL"],
  },
  {
    id: "a2",
    type: "Review",
    oa: true,
    subject: "Bayesian Cognition",
    title: "Resource-rational analysis at ten years: what we got right, what we missed, and what comes next",
    authors: [
      { name: "F. Lieberman", corresp: true, aff: 1 },
      { name: "A. Okafor", aff: 2 },
    ],
    affiliations: [
      "Princeton Neuroscience Institute",
      "Institute of Cognitive Neuroscience, UCL",
    ],
    abstract: "A decade after the introduction of resource-rational analysis, we audit its predictions against the empirical record, identify three classes of phenomena it has consistently underpredicted, and propose a reformulation in which the cost of computation is endogenous to the agent's policy. The reformulation absorbs prospect-theoretic anomalies as a special case.",
    doi: "10.31472/jcc.2026.0414",
    pages: "61–103",
    volume: 18,
    issue: 2,
    year: 2026,
    publishedOn: "May 10, 2026",
    receivedOn: "Dec 1, 2025",
    citations: 7,
    downloads: "5,902",
    altmetric: 318,
    altmetricBreakdown: { news: 11, twitter: 86, blogs: 14, policy: 2 },
    keywords: ["bounded rationality", "review", "decision making"],
  },
  {
    id: "a3",
    type: "Research Article",
    oa: true,
    subject: "Memory & Recall",
    title: "A two-process model of episodic encoding under uncertainty, validated against 11 fMRI datasets",
    authors: [
      { name: "S. Castellanos", corresp: true, aff: 1 },
      { name: "J. Park", aff: 1 },
      { name: "R. Iyer", aff: 2 },
      { name: "T. Mwangi", aff: 3 },
      { name: "B. Klein", aff: 4 },
    ],
    affiliations: [
      "Max Planck Institute for Human Cognitive and Brain Sciences",
      "Stanford Department of Statistics",
      "African Institute for Mathematical Sciences",
      "Hebrew University of Jerusalem",
    ],
    abstract: "We propose a hierarchical two-process model in which fast pattern separation and slow gist consolidation compete for representational capacity as a function of perceived encoding uncertainty. Across eleven public fMRI datasets (n = 1,841), the model recovers individual differences in subsequent-memory effects with a held-out R² of 0.41.",
    doi: "10.31472/jcc.2026.0409",
    pages: "22–60",
    volume: 18,
    issue: 2,
    year: 2026,
    publishedOn: "May 4, 2026",
    receivedOn: "Sep 22, 2025",
    citations: 9,
    downloads: "2,471",
    altmetric: 88,
    altmetricBreakdown: { news: 2, twitter: 24, blogs: 3, policy: 0 },
    keywords: ["episodic memory", "fMRI", "uncertainty", "hierarchical model"],
  },
  {
    id: "a4",
    type: "Short Report",
    oa: true,
    subject: "Neural Computation",
    title: "Phase coding survives 60-fold network dilution in liquid state machines",
    authors: [
      { name: "Y. Tanaka", corresp: true, aff: 1 },
      { name: "C. Rasmussen", aff: 2 },
    ],
    affiliations: [
      "RIKEN Center for Brain Science",
      "Niels Bohr Institute, University of Copenhagen",
    ],
    abstract: "Contrary to recent claims, we find that phase-coded readouts in liquid state machines remain accurate at dilution levels well beyond what was previously thought possible, provided the readout layer is allowed to compensate via a single learned phase offset per channel.",
    doi: "10.31472/jcc.2026.0401",
    pages: "12–21",
    volume: 18,
    issue: 2,
    year: 2026,
    publishedOn: "Apr 28, 2026",
    receivedOn: "Feb 3, 2026",
    citations: 3,
    downloads: "1,206",
    altmetric: 41,
    altmetricBreakdown: { news: 0, twitter: 18, blogs: 2, policy: 0 },
    keywords: ["liquid state machine", "phase coding", "reservoir computing"],
  },
  {
    id: "a5",
    type: "Research Article",
    oa: true,
    subject: "Computational Psychiatry",
    title: "Computational signatures of compulsive checking across 4,200 participants and three diagnostic boundaries",
    authors: [
      { name: "N. Aldridge", corresp: true, aff: 1 },
      { name: "E. Fernández", aff: 2 },
      { name: "M. Tóth", aff: 3 },
    ],
    affiliations: [
      "Institute of Psychiatry, King's College London",
      "Universidad Autónoma de Madrid",
      "ETH Zürich",
    ],
    abstract: "We fit a partially-observable Markov decision process to data from 4,200 participants spanning subclinical, clinical OCD, and remitted OCD groups. Two parameters — termination noise and belief-update gain — separate clinical from remitted participants with AUC 0.84, suggesting concrete targets for closed-loop intervention.",
    doi: "10.31472/jcc.2026.0395",
    pages: "1–11",
    volume: 18,
    issue: 2,
    year: 2026,
    publishedOn: "Apr 21, 2026",
    receivedOn: "Oct 14, 2025",
    citations: 18,
    downloads: "7,330",
    altmetric: 612,
    altmetricBreakdown: { news: 31, twitter: 142, blogs: 19, policy: 4 },
    keywords: ["OCD", "POMDP", "computational psychiatry"],
  },
  {
    id: "a6",
    type: "Tutorial",
    oa: true,
    subject: "Reviews & Tutorials",
    title: "A practitioner's guide to identifiability in cognitive model fitting",
    authors: [
      { name: "R. Iyer", corresp: true, aff: 1 },
      { name: "L. Marchetti", aff: 2 },
    ],
    affiliations: [
      "Stanford Department of Statistics",
      "ETH Zürich",
    ],
    abstract: "Half of published cognitive-model parameters fail standard identifiability checks. We provide a decision tree, runnable code, and four worked examples that together cover the diagnostic landscape most experimentalists will actually encounter.",
    doi: "10.31472/jcc.2026.0388",
    pages: "139–172",
    volume: 18,
    issue: 1,
    year: 2026,
    publishedOn: "Feb 18, 2026",
    receivedOn: "Aug 30, 2025",
    citations: 28,
    downloads: "11,402",
    altmetric: 287,
    altmetricBreakdown: { news: 6, twitter: 71, blogs: 18, policy: 0 },
    keywords: ["model fitting", "identifiability", "tutorial"],
  },
  {
    id: "a7",
    type: "Research Article",
    oa: true,
    subject: "Decision Making",
    title: "Anchoring effects vanish when participants are paid for calibration, not accuracy",
    authors: [
      { name: "E. Fernández", corresp: true, aff: 1 },
      { name: "P. Adebayo", aff: 2 },
    ],
    affiliations: [
      "Universidad Autónoma de Madrid",
      "Humboldt-Universität zu Berlin",
    ],
    abstract: "Across six preregistered experiments (n = 2,206), the canonical anchoring effect is eliminated when participants are scored on a proper calibration rule rather than on point accuracy. We argue that anchoring reflects a sensible response to ambiguous incentives, not a bias.",
    doi: "10.31472/jcc.2026.0371",
    pages: "73–112",
    volume: 18,
    issue: 1,
    year: 2026,
    publishedOn: "Feb 2, 2026",
    receivedOn: "May 17, 2025",
    citations: 41,
    downloads: "8,915",
    altmetric: 521,
    altmetricBreakdown: { news: 24, twitter: 118, blogs: 11, policy: 3 },
    keywords: ["anchoring", "calibration", "preregistration"],
  },
  {
    id: "a8",
    type: "Research Article",
    oa: true,
    subject: "Language & Symbols",
    title: "Compositional generalization in transformer language models predicts no behavioral signature in adults",
    authors: [
      { name: "B. Klein", corresp: true, aff: 1 },
      { name: "Y. Tanaka", aff: 2 },
      { name: "F. Lieberman", aff: 3 },
    ],
    affiliations: [
      "Hebrew University of Jerusalem",
      "RIKEN Center for Brain Science",
      "Princeton Neuroscience Institute",
    ],
    abstract: "We adapt three benchmark probes of compositional generalization from the NLP literature to human participants and find no behavioral signature of the model–human gap reported in synthetic studies. Implications for the use of LMs as cognitive models are discussed.",
    doi: "10.31472/jcc.2026.0362",
    pages: "33–72",
    volume: 18,
    issue: 1,
    year: 2026,
    publishedOn: "Jan 24, 2026",
    receivedOn: "Jul 8, 2025",
    citations: 22,
    downloads: "6,124",
    altmetric: 209,
    altmetricBreakdown: { news: 4, twitter: 61, blogs: 9, policy: 1 },
    keywords: ["compositionality", "language models", "behavior"],
  },
];

const ISSUES = [
  { v: 18, i: 2, year: 2026, month: "May", topic: "Predictive models of cognition", current: true, articles: 14 },
  { v: 18, i: 1, year: 2026, month: "Feb", topic: "Identifiability & inference", current: false, articles: 11 },
  { v: 17, i: 4, year: 2025, month: "Nov", topic: "Computational psychiatry", current: false, articles: 9 },
  { v: 17, i: 3, year: 2025, month: "Aug", topic: "Memory in noisy systems", current: false, articles: 12 },
  { v: 17, i: 2, year: 2025, month: "May", topic: "Language & abstraction", current: false, articles: 10 },
  { v: 17, i: 1, year: 2025, month: "Feb", topic: "Open issue", current: false, articles: 13 },
];

window.JOURNAL = JOURNAL;
window.SUBJECTS = SUBJECTS;
window.ARTICLES = ARTICLES;
window.ISSUES = ISSUES;
